#!/bin/bash
# rmake for rlabplus: cfitsio
# (c) Marijan Kostrun, 2014, 2023, 2024

# rlab source location
RLAB_SDK=/usr/local/include/rlab

# garbage collector include directory. part of the rlab source tree.
GC_RLAB=$RLAB_SDK/gc

CFITSIO_SO="-lcfitsio"
HOSTTYPE=`uname -i`
if [ "$HOSTTYPE" = "x86_64" ]; then
  CFITSIO_RLAB_SO=rlabplus_lib64cfitsio.so
else
  CFITSIO_RLAB_SO=rlabplus_libcfitsio.so
fi

# create so
# note: CFLAGS have to be the same as those used in building the rlab
echo -n "Building CFITSIO bindings for rlabplus"
rc=`gcc $CFLAGS -fPIC -c r_cfitsio.c -I$RLAB_SDK -I$GC_RLAB -I./include 2>&1`
[ -z "$rc" ] || (echo "$rc"; exit)
if [ -z "$rc" ]; then
  gcc -Wall -shared -fPIC -o $CFITSIO_RLAB_SO r_cfitsio.o $CFITSIO_SO
  rm r_cfitsio.o
  echo " . Done!"
fi
