#!/bin/bash
# rmake for rlabplus: gpib
# (c) Marijan Kostrun, 2006, 2010

# rlab source location
RLAB_SDK=/usr/local/include/rlab

# garbage collector include directory. part of the rlab source tree.
GC_RLAB=$RLAB_SDK/gc

# gpib library:
# making it work with NI's GPIB-USB-HS
# 1. for 64 bit opensuse 11.2 system, the gpib-library was configured as follows:
#     ./configure --libdir=/usr/lib64/
# 2. modified /etc/gpib.conf to contain
# interface {
#         minor = 0               /* board index, minor = 0 uses /dev/gpib0, minor = 1 uses /dev/gpib1, etc. */
#         board_type = "ni_usb_b" /* type of interface board being used */
#         name = "ni_usb"         /* optional name, allows you to get a board descriptor using ibfind() */
#         pad = 0                 /* primary address of interface             */
#         sad = 0                 /* secondary address of interface           */
#         timeout = T3s           /* timeout for commands */
#
#         eos = 0x0a      /* EOS Byte, 0xa is newline and 0xd is carriage return */
#         set-reos = yes  /* Terminate read if EOS */
#         set-bin = no    /* Compare EOS 8-bit */
#         set-xeos = no   /* Assert EOI whenever EOS byte is sent */
#         set-eot = yes   /* Assert EOI with last byte on writes */
#
#         master = yes    /* interface board is system controller */
# }

# 3. edited /etc/modprobe.conf.local to contain:
#     alias char-major-160 gpib_common
#     alias gpib0 ni_usb_gpib
#     install ni_usb_gpib PATH=/sbin:/usr/sbin:/usr/local/sbin:$PATH;modprobe --ignore-install ni_usb_gpib; \
#         gpib_config --minor 0
# (or just plainly execute /usr/local/sbin/gpib_config --minor 0)
HOSTTYPE=`uname -i`
if [ "$HOSTTYPE" = "x86_64" ]; then
  GPIB_SO=/usr/local/lib64/libgpib.so
  GPIB_RLAB_SO=rlabplus_lib64gpib.so
else
  GPIB_SO=/usr/local/lib/libgpib.so
  GPIB_RLAB_SO=rlabplus_libgpib.so
fi

# create so
# note: CFLAGS have to be the same as those used in building the rlab
echo -n "Building GPIB bindings for rlabplus"
rc=`gcc $CFLAGS -fPIC -c rlabplus_gpib.c -I$RLAB_SDK -I$GC_RLAB 2>&1`
[ -z "$rc" ] || (echo "$rc"; exit)
if [ -z "$rc" ]; then
  gcc -Wall -shared -fPIC -o $GPIB_RLAB_SO rlabplus_gpib.o $GPIB_SO
  rm rlabplus_gpib.o
  echo " . Done!"
fi
