#!/bin/bash
# rmake for rlabplus: ngspice
# (c) Marijan Kostrun, 2013, 2023

# rlab source location
RLAB_SDK=/usr/local/include/rlab

# garbage collector include directory. part of the rlab source tree.
GC_RLAB=$RLAB_SDK/gc

NGSPICE_SO=-lngspice
HOSTTYPE=`uname -i`
if [ "$HOSTTYPE" = "x86_64" ]; then
  NGSPICE_RLAB_SO=rlabplus_lib64ngspice.so
else
  NGSPICE_RLAB_SO=rlabplus_libngspice.so
fi

# create so
# note: CFLAGS have to be the same as those used in building the rlab
echo -n "Building NGSPICE bindings for rlabplus"
rc=`gcc $CFLAGS -fPIC -c r_ngspice.c -I$RLAB_SDK -I$GC_RLAB -I./ 2>&1`
[ -z "$rc" ] || (echo "$rc"; exit)
if [ -z "$rc" ]; then
  gcc -Wall -shared -fPIC -o $NGSPICE_RLAB_SO r_ngspice.o $NGSPICE_SO
  rm r_ngspice.o
  echo " . Done!"
fi
