#!/bin/bash
# rmake for rlabplus: gphoto2
# (c) Marijan Kostrun, 2013, 2023

# rlab source location
RLAB_SDK=/usr/local/include/rlab

# garbage collector include directory. part of the rlab source tree.
GC_RLAB=$RLAB_SDK/gc

GPHOTO2_SO="-lgphoto2 -lgphoto2_port"
HOSTTYPE=`uname -i`
if [ "$HOSTTYPE" = "x86_64" ]; then
  GPHOTO2_RLAB_SO=rlabplus_lib64gphoto2.so
else
  GPHOTO2_RLAB_SO=rlabplus_libgphoto2.so
fi

# create so
# note: CFLAGS have to be the same as those used in building the rlab
echo -n "Building GPHOTO2 bindings for rlabplus"
rc=`gcc $CFLAGS -fPIC -c r_gphoto2.c -I$RLAB_SDK -I$GC_RLAB -I./include 2>&1`
[ -z "$rc" ] || (echo "$rc"; exit)
if [ -z "$rc" ]; then
  gcc -Wall -shared -fPIC -o $GPHOTO2_RLAB_SO r_gphoto2.o $GPHOTO2_SO
  rm r_gphoto2.o
  echo " . Done!"
fi
